// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5AmzAmCQCzPfdBDziVKQyXK06s2Fe5b8',
    appId: '1:785933882714:web:3ace1e842662df7a070f63',
    messagingSenderId: '785933882714',
    projectId: 'project99-4e4fe',
    authDomain: 'project99-4e4fe.firebaseapp.com',
    storageBucket: 'project99-4e4fe.firebasestorage.app',
    measurementId: 'G-NM1TM75GVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGw0BOmaodsIUKMCQ3My1lL2rqXxe83U',
    appId: '1:785933882714:android:8209e68ee240fb32070f63',
    messagingSenderId: '785933882714',
    projectId: 'project99-4e4fe',
    storageBucket: 'project99-4e4fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmGvnTrxYLX8WcoKXS-U-k5vtGkl7Vzg8',
    appId: '1:785933882714:ios:ac00fc8fee105042070f63',
    messagingSenderId: '785933882714',
    projectId: 'project99-4e4fe',
    storageBucket: 'project99-4e4fe.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmGvnTrxYLX8WcoKXS-U-k5vtGkl7Vzg8',
    appId: '1:785933882714:ios:ac00fc8fee105042070f63',
    messagingSenderId: '785933882714',
    projectId: 'project99-4e4fe',
    storageBucket: 'project99-4e4fe.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5AmzAmCQCzPfdBDziVKQyXK06s2Fe5b8',
    appId: '1:785933882714:web:9452ed35da0c01ce070f63',
    messagingSenderId: '785933882714',
    projectId: 'project99-4e4fe',
    authDomain: 'project99-4e4fe.firebaseapp.com',
    storageBucket: 'project99-4e4fe.firebasestorage.app',
    measurementId: 'G-Q7DGFNZ6SQ',
  );
}
